#!/bin/bash
# Embeds setup/cmcr-imac-setup.sh into CMCRCore (Sources/CMCRCore/SetupScriptTemplate.swift), so the app and
# cmcrctl ship exactly the reviewed script. Run after every change of the script; the unit test
# `embeddedSetupScriptMatchesRepository` fails while the two copies differ.
#   scripts/embed-setup.sh           – regenerate
#   scripts/embed-setup.sh --check   – only verify (exit 1 when out of date)
set -euo pipefail
cd "$(dirname "$0")/.."
SRC=setup/cmcr-imac-setup.sh
OUT=Sources/CMCRCore/SetupScriptTemplate.swift

bash -n "$SRC"
# The script is embedded in a ##"""…"""## raw string: these sequences would end or interpolate it.
if grep -q -e '"""##' -e '\\##' "$SRC"; then
  echo "$SRC zawiera \"\"\"## lub \\## – nie można go osadzić w Swift." >&2
  exit 1
fi

TMP="$(mktemp "${TMPDIR:-/tmp}/cmcr-embed.XXXXXX")"
trap 'rm -f "$TMP"' EXIT
{
  echo "// Generated by scripts/embed-setup.sh from setup/cmcr-imac-setup.sh – do not edit by hand."
  echo
  echo "enum SetupScriptTemplate {"
  echo "    static let text = ##\"\"\""
  cat "$SRC"
  echo
  echo "\"\"\"##"
  echo "}"
} > "$TMP"

if [ "${1:-}" = "--check" ]; then
  if cmp -s "$TMP" "$OUT"; then echo "Wbudowany skrypt jest aktualny."; exit 0; fi
  echo "$OUT jest nieaktualny – uruchom scripts/embed-setup.sh" >&2
  exit 1
fi
cp "$TMP" "$OUT"
echo "Zapisano $OUT"
